pdf_folder: /home/prestige/Documents/sangam/karyashala/annotes/test
notes_folder: /home/prestige/Documents/sangam/karyashala/annotes/notes
scheduler_settings:
  interval_minutes: 1
  auto_start_on_boot: false
output_settings:
  annotated_file_format: .md
  annotated_file_prefix: Notes -
  annotated_file_suffix: ''
  annotated_file_tags:
  - annotated
  - pdf_notes
  page_link_settings:
    include_page_links: true
    visible_links: false
    link_style: wikilinks
  yaml_front_matter_settings:
    include_yaml_front_matter: true
    yaml_front_matter_keys:
    - title
    - created
    - modified
    - tags
  include_images: 'false'
markdown_settings:
  tab_size: 4
  linking_style: wikilinks
  bold_highlights: true
  italic_comments: true
  preserve_indentation: true
annotation_settings:
  symbol_indent: '-'
  symbol_add_to_last_highlight: +
  symbol_add_text: /
  symbol_quote:
  - '>>'
  - .quote
  symbol_todo:
  - .todo
  - '- [ ]'
  symbol_heading:
  - .h1
  - '#'
  annotated_notes_section_title: Notes
notification_settings:
  show_on_sync: true
  show_on_error: true
  sound_enabled: false
info_section_settings:
  include_info_section: true
  info_section_title: Document Info
  info_section_items:
  - Title
  - Pages
  - Annotated pages
  - Total annotations
  - First annotated on page
  - Last annotated on page
  - First annotated at
  - Last annotated at
debug_mode: false
